# permissions to do viewer kafkabenches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkabench-viewer-role
rules:
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - kafkabenches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - kafkabenches/status
  verbs:
  - get
