# permissions to do viewer ocplogtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocplogtest-viewer-role
rules:
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ocplogtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ocplogtests/status
  verbs:
  - get
