
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - drills
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - drills/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - drills/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - fios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - fios/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - fios/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - iopings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - iopings/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - iopings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - iperf3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - iperf3s/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - iperf3s/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - kafkabenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - kafkabenches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ocplogtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ocplogtests/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ocplogtests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - pgbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - pgbenches/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - pgbenches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - qperves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - qperves/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - qperves/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - s3benches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - s3benches/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - s3benches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - sysbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - sysbenches/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - sysbenches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ycsbbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ycsbbenches/finalizers
  verbs:
  - update
- apiGroups:
  - perf.kubestone.xridge.io
  resources:
  - ycsbbenches/status
  verbs:
  - get
  - patch
  - update
