---
apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: Iperf3
metadata:
  name: iperf3-tests
spec:
  image:
    name: xridge/iperf3:3.7.0
    pullPolicy: IfNotPresent

  serverConfiguration:
    cmdLineArgs: --json
    podLabels:
      iperf-mode: server

    podScheduling:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - store
            topologyKey: "kubernetes.io/hostname"
    hostNetwork: false
    
  clientConfiguration:
    cmdLineArgs: --json
    podLabels:
      iperf-mode: client
    podScheduling:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: iperf-mode
                operator: In
                values:
                - server
            topologyKey: "kubernetes.io/hostname"

  udp: false
