apiVersion: batch/v1
kind: Job
metadata:
  name: fio-test-job
spec:
  template:
    metadata:
      labels:
        app: fio-test
    spec:
      containers:
        - name: fio-container
          image: xridge/fio:3.13
          command: ["sleep", "100000"]
          volumeDevices:
            - name: data
              devicePath: /dev/sdb
          securityContext:
            privileged: true
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc
